### PR TITLE
Added a stat handler and load time stats

### PR DESCRIPTION
**Pull request by GoryMoon**
The time stat saves the total time spent in the loading screen and shows that together with the current loading time, the average loading time and the amount of start that have been done.
The stats can be disabled in the stats file.

The stat handler can be used for a lot more things and the time stats can be used as examples.
Can be used as a score keeping, settings or similar stuff.

### CODE REVIEW

**Comment by jaredlll08** [comment]
Where exactly does it make the stat file?

**Comment by GoryMoon** [comment]
In the mc folder, can be changed.
Was thinking if it would be global for all instances or just the instance, decided to just do it per instance as the load time more would be more to compare with other starts of that instance. 
The stats file is a JSON file that can be read and changed

**Comment by jaredlll08** [comment]
Could you move the file to the config folder then? no need to make the root dir a mess.
Also why aren't you just using the run dir for the file location?

```java
new File("test.txt");
```
would make a file in the instance directory (like where options.txt is)

**Comment by GoryMoon** [comment]
Moved it to the config now.
Had the same as the uuid cache for that, works without. The splash.properties uses the mcdir, don't really know why it's used sometimes and sometimes not in vanilla and forge.

**Comment by jaredlll08** [comment]
Uh, the splash properties file is in the Config dir... Always has been

**Comment by GoryMoon** [comment]
I meant it uses the mcdir as the base dir and not base it on the instance dir.
`new File(Minecraft.getMinecraft().mcDataDir, "config/splash.properties");`

**Pull request merged**
